# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 644e7a805e52304de00639970de398ff92d009b4936ef2a06214a354a5978e16a4b303de0985c063136ef8f852af198d64c2fe3a7d0a3d2d5975385f76f668b4

test:
  secret_key_base: 264d25590bb8dcd8e535c0f3947179daaa61aa54c04e60a7cf9a727b5c2d01230e1c408820046cfd2d90236b5b1d32fb75299beda48d86edf939006514c1b007

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
